<div class="main">
	<div class="my_sme_vychod"></div>
	<div class="main_desc">
		je séria koncertov a podujatí<br />
		v centrách miest na východe Slovenska,<br />
		na ktorých budú známi umelci z Východu<br />
		baviť všetkých srdcom Východniarov.<br /><br />
		<span>
			Príďte sa aj vy zabaviť<br />
			do svojho mesta!
		</span>
	</div>
	<div class="main_boxes">
		<a href="#" class="active">
			<div class="box box_01 b_right b_bottom">
				<div class="box_orig">
					<div class="orig_title">SPIŠSKÁ<br />NOVÁ VES</div>
					<div class="orig_date">21. jún 2014</div>
				</div>
				<div class="box_hover">
					<div class="hover_title">SPIŠIAK<br />Čakáme Ťa doma</div>
					<div class="hover_desc">
						ŽOBRÁCI a Michal Hudák<br />
						<span>IMT Smile</span><br />
						Katka Knechtová
					</div>
				</div>
			</div>
		</a>
		<a href="#" class="active">
			<div class="box box_02 b_right b_bottom">
				<div class="box_orig">
					<div class="orig_title">SNINA</div>
					<div class="orig_date">29. jún 2014</div>
				</div>
				<div class="box_hover">
					<div class="hover_title">Sninčan<br />Čakáme Ťa doma</div>
					<div class="hover_desc">
						ŽOBRÁCI a Michal Hudák<br />
						<span>Chiki Liki Tu-a</span><br />
						Katka Knechtová
					</div>
				</div>
			</div>
		</a>
		<a href="#" class="active">
			<div class="box box_03 b_bottom">
				<div class="box_orig">
					<div class="orig_title">bardejov</div>
					<div class="orig_date">9. august 2014</div>
				</div>
				<div class="box_hover">
					<div class="hover_title">bardejovčan<br />Čakáme Ťa doma</div>
					<div class="hover_desc">
						M. Čekovský<br />
						<span>Katka Knechtová</span><br />
						Peter Bič Projekt
					</div>
				</div>
			</div>
		</a>

		<a href="#" class="active">
			<div class="box box_04 b_right b_bottom">
				<div class="box_orig">
					<div class="orig_title">stropkov</div>
					<div class="orig_date">19. júl 2014</div>
				</div>
				<div class="box_hover">
					<div class="hover_title">stropkovčan<br />Čakáme Ťa doma</div>
					<div class="hover_desc">
						ŽOBRÁCI a Michal Hudák<br />
						<span>Chiki Liki Tu-a</span><br />
						Katka Knechtová
					</div>
				</div>
			</div>
		</a>
		<!-- <a href="#" class="active"> -->
			<div class="box box_05 b_right b_bottom">
				<div class="box_orig">
					<div class="orig_title">príďte stretnúť<br />východniarov,<br />ktorí robia<br />veci</div>
					<div class="orig_date"></div>
				</div>
				<div class="box_hover">

				</div>
			</div>
		<!-- </a> -->
		<a href="#" class="active">
			<div class="box box_06 b_bottom">
				<div class="box_orig">
					<div class="orig_title">humenné</div>
					<div class="orig_date">2. august 2014</div>
				</div>
				<div class="box_hover">
					<div class="hover_title">humenčan<br />Čakáme Ťa doma</div>
					<div class="hover_desc">
						ŽOBRÁCI a Michal Hudák<br />
						<span>M. Čekovský</span><br />
						Peter Bič Projekt
					</div>
				</div>
			</div>
		</a>

		<a href="#" class="active">
			<div class="box box_07 b_right">
				<div class="box_orig">
					<div class="orig_title">revúca</div>
					<div class="orig_date">23. august 2014</div>
				</div>
				<div class="box_hover">
					<div class="hover_title">revúčan<br />Čakáme Ťa doma</div>
					<div class="hover_desc">
						ŽOBRÁCI a Michal Hudák<br />
						<span>Katka Knechtová</span><br />
						Peter Bič Projekt
					</div>
				</div>
			</div>
		</a>
		<a href="#" class="active">
			<div class="box box_08 b_right">
				<div class="box_orig">
					<div class="orig_title">michalovce</div>
					<div class="orig_date">31. august 2014</div>
				</div>
				<div class="box_hover">
					<div class="hover_title">michalovčan<br />Čakáme Ťa doma</div>
					<div class="hover_desc">
						ŽOBRÁCI a Michal Hudák<br />
						<span>IMT Smile</span><br />
						Katka Knechtová
					</div>
				</div>
			</div>
		</a>
		<a href="#" class="active">
			<div class="box box_09">
				<div class="box_orig">
					<div class="orig_title">veľký šariš</div>
					<div class="orig_date">deň otvorených<br />dverí<br />6. september 2014</div>
				</div>
				<div class="box_hover">

				</div>
			</div>
		</a>
	</div>
</div>